services:
  - type: web
    name: k33p-backend
    env: node
    nodeVersion: 18.x # Deployment will use Node.js 18.x while local development uses 22.14.0
    region: oregon # Choose the region closest to your users
    plan: free # Upgrade to a paid plan for production
    buildCommand: cd backend && npm ci --legacy-peer-deps --include=dev && npx tsc && node fix-imports.js
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: BLOCKFROST_API_KEY
        sync: false # This will be set manually in the Render dashboard
      - key: SEED_PHRASE
        sync: false # This will be set manually in the Render dashboard
      - key: PORT
        value: 3000
    autoDeploy: true